### ISSUE TITLE
Required Docs and Pascal Case Columns

### ISSUE THREAD

**Issue by dallyhorton** [tnightengale/dbt-meta-testing#1]
When running `dbt run-operation required_docs` against my models, every column was coming back saying it wasn't documented. I realised this was a case issue, so removed the 'column | lower' within evaluate_required_docs.sql. Now everything works perfectly.

Not sure what the solution is. I assume there's a reason the 'column | lower' was added? Can we have a flag indicating if a case sensitive comparison is required?

Great package by the way. Thanks for sharing.

**Comment by tnightengale** [comment]
@dallyhorton that's really interesting!

I added it because I assumed that all columns were being catalogued in lowercase within the `graph` context variable. But perhaps that is not the case.

Can you share any dbt version details from your run?

**Comment by dallyhorton** [comment]
Sure thing. We're using dbt 0.18.1 with the dbt-spark plugin (also 0.18.1). We're running against an Azure Databricks environment (in case that helps). I really wish I knew more about how dbt works behind the scenes.

**Comment by tnightengale** [comment]
Hmmm... I think the answer here is to add integration tests for the dbt-spark plugin. Currently, the only "official" warehouse that has been validated via integration tests is Snowflake. It sounds like you found a fix, so I'm tentatively going to put this as a lower priority relative to other issues.
