### ISSUE TITLE
Customize required_docs

### ISSUE THREAD

**Issue by tuanchris** [tnightengale/dbt-meta-testing#13]
Hi there,

Thank you, this repo is great! 

One quick suggestion, it would be great if we can customize the required docs settings. Meaning we can choose from the list below, instead of enforcing all three of them. 

- The model has a non-empty description
- The columns in the model are specified in the model .yml
- The columns specified in the model .yml have non-empty descriptions

**Comment by tnightengale** [comment]
First off, thank you! My thinking around this is to clarify the opinions of the package in the docs: it aims to be opinionated about complete coverage. 

If complete coverage is difficult, it's probably more of a problem around creating complete docs with ease. Packages like https://github.com/dbt-labs/dbt-codegen can help with that.

Indeed, in my project I use a modified version of the aforementioned packed to populate docs automatically with existing descriptions.
