### ISSUE TITLE
Is the latest version compatible with dbt 0.20.0

### ISSUE THREAD

**Issue by garivaldo** [tnightengale/dbt-meta-testing#15]
Not sure if this is the place to ask this, so let me know if it isn't.

I wanted to verify if dbt-meta-testing version 0.3.2 is compatible with dbt 0.20.0. It seems like it isn't because it's dependent on dbt_utils [">=0.6.0", "<0.7.0"], but dbt 0.20.0 requires dbt_utils 0.7.0. 

If so, when do think dbt-meta-testing will be upgraded?

**Comment by tnightengale** [comment]
Thanks for choosing dbt-meta-testing!

I plan to upgrade it this weekend 👍🏼


Cheers,

Teghan

**Comment by meurant-naude** [comment]
Just an FYI:
I'm getting this error when I run `dbt deps`
```
Running with dbt=0.20.0
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```
If I remove your package, I don't get the error.

**Comment by tnightengale** [comment]
@meurant-naude good call out - I will look into that when upgrading to be compatible with dbt 0.20! Thanks

**Comment by tnightengale** [comment]
Patch 0.3.3 is compatible with dbt 0.20.0.

**Comment by meurant-naude** [comment]
Awesome, thanks.
```
Installing tnightengale/dbt_meta_testing@0.3.3
  Installed from version 0.3.3
```
Success!
