### ISSUE TITLE
Doesn't work with dbt v1.0.0

### ISSUE THREAD

**Issue by jzamanxometry** [tnightengale/dbt-meta-testing#19]
It seems this line https://github.com/tnightengale/dbt-meta-testing/blob/master/dbt_project.yml#L6 is preventing this repo to be compaitible with dbt v1.0.0

It would be great if we can update the version to fix this issue. I've opened up this PR to address it: https://github.com/tnightengale/dbt-meta-testing/pull/20

**Comment by tnightengale** [comment]
Closed by #21 Thank you for the assistance!
