### ISSUE TITLE
0.3.0 Release

### ISSUE THREAD

**Issue by tnightengale** [tnightengale/dbt-meta-testing#3]
Courtesy of @jtalmi:

> i’d like to extend it for two use cases:
> model must have one of X tests, where X can be [‘unique’, ‘unique_where’, ‘unique_combinations_of_columns’], etc.
> model must have one of X tags, where X can be [‘hourly’, ‘nightly’, ‘weekly’], etc.
> this involves a bit of a shift in the current way the package operates, and i’d be curious to know your thoughts on how to implement it. my initial thoughts are passing in some sort of operation like:
> ```
> +required_tests: {"unique | unique_where | unique_threshold": 1, "not_null": 1}
> ```
> and the model parses that as requiring one of unique/unique_where/unique_threshold. can also wrap ths in a var like var(‘unique_tests’)
> other options i can think of off the top of my head include making use of the regex functionality in dbt 0.19, e.g. {'.+unique.+': 1} , or adding something like:
> ```
> +required_tests:
>   - unique:
>     - count: 1
>       tests: 
>        - unique
>        - unique_where
>   - not_null
> ```

**Comment by tnightengale** [comment]
I really like this proposal: especially the `OR` functionality. 

I am going to try and get #2 merged next weekend. After that, I'd like to combine the `validate_tests` and `validate_docs` in a single `validate` function.

I'm thinking this will will take two args: `{% macro validate(config, contract) %}` where `contract` represents almost like a type object. I'd like to have the `OR` functionality be one of these type objects. Obviously there are limits to Jinja, but it would be cool to see if it's possible. 

With that in-place, adding a `required_tags` macro should be fairly straight forward.

**Comment by jtalmi** [comment]
That's great. I'm can submit a PR for that, or add the required_tags feature afterward. Let me know if that's alright.

**Comment by tnightengale** [comment]
Bumping this functionality to the potential 0.3 release as 0.2 is now available; consisting mostly of a test harness and error refactoring

**Comment by tnightengale** [comment]
@jtalmi closed with #9
