### ISSUE TITLE
required_docs failed message not rendering on screen.

### ISSUE THREAD

**Issue by akhaitan-xometry** [tnightengale/dbt-meta-testing#4]
When I am using dbt 0.19.0 with this package v 0.2.0, when the validation fails, the message is not being displayed. 
The problem was not happening when I was using 0.18.x version or when I negate package version to 0.1.2.
![image](https://user-images.githubusercontent.com/56896023/114088414-fe076500-9882-11eb-92d8-8d87e9dcc67c.png)

**Comment by tnightengale** [comment]
@akhaitan-xometry Thanks for raising this! That's really interesting... 0.2 was a big refactor on the error messages and how they are returned. Can I grab some more details? What warehouse are you running your project on?

**Comment by akhaitan-xometry** [comment]
> @akhaitan-xometry Thanks for raising this! That's really interesting... 0.2 was a big refactor on the error messages and how they are returned. Can I grab some more details? What warehouse are you running your project on?

It is on snowflake but this test was done on an AWS Postgres instance.

**Comment by StijnZanders** [comment]
The issue seems to be in line 19 of `macros/utils/errors/error_required_docs.sql`:
`{% if missing_description_errors | length > 0 %}`
Should be
`{% if missing_model_errors | length > 0 %}`

**Comment by tnightengale** [comment]
Fixed by https://github.com/tnightengale/dbt-meta-testing/releases/tag/0.2.1
